### ISSUE TITLE
problem while installing

### ISSUE THREAD

**Issue by andriej** [basnijholt/addon-otmonitor#1]
After adding repo to add-on supervisor, I've clicked install and got error in popup.
Error comes from cloudflare which is my proxy in-between for nginx (and securing whole installation).

There is no issue with that regarding other ingress addons - I'd like to give otmonitor a spin.
How can I help you debug?

**Comment by andriej** [comment]
despite the error addon added itself.

**Comment by basnijholt** [comment]
Good that you got it to work!
