### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by mories76** [basnijholt/addon-otmonitor#10]
No issue;-)
Just found and installed this addon earlier today, after soldering my OTGW.
Great stuff!

**Comment by basnijholt** [comment]
That's great! Please Star this repo if you use it 👍

It will give others a sense of it being used, so they’re more eager to try it out.

**Comment by andriej** [comment]
Key to success would be to add it as 'community addon', but to do that it still need some tweaks

**Comment by basnijholt** [comment]
What's a "community addon"?

**Comment by andriej** [comment]
![image](https://user-images.githubusercontent.com/6303489/96354283-42385a80-10d5-11eb-9715-556652b37cdf.png)
