### ISSUE TITLE
otmonitor add-on does not install (Home Assistant Core 2020.12.0)

### ISSUE THREAD

**Issue by JarichSpliethoff** [basnijholt/addon-otmonitor#11]
When I try to install the otmonitor add-on through Supervisor, I get the error message:

_The command '/bin/bash -o pipefail -c ./tclkit sdx.kit wrap otmonitor -runtime runtime && cp otmonitor /opt/otmonitor &&chmod +x /opt/otmonitor' returned a non-zero code:126_

![afbeelding](https://user-images.githubusercontent.com/22955519/102091520-38a24900-3e1f-11eb-8c1a-1802c3a4433f.png)

I'm running Home Assistant Core 2020.12.0

What could be the problem?

**Comment by basnijholt** [comment]
What CPU arch do you have?

**Comment by JarichSpliethoff** [comment]
I'm running HA Core on a Raspberry pi 4 8gb, so a Broadcom 2711, Quad-core Cortex-A72 64-bit SoC @ 1.5GHz

**Comment by CodingRick** [comment]
Could be this line: https://github.com/basnijholt/addon-otmonitor/blob/13d805186060372b39e249653faee577692319f6/otmonitor/Dockerfile#L32

Shouldn't aarch64 be using http://otgw.tclcode.com/download/tclkit-aarch64 ?

**Comment by basnijholt** [comment]
I've just pushed https://github.com/basnijholt/addon-otmonitor/commit/65bd5613da03329ef398b80dd6b4021c61b659f1
Could you try again?

**Comment by JarichSpliethoff** [comment]
Thanks for helping. I've done the following:
added the add-on repositorty again: "https://github.com/basnijholt/addon-otmonitor" and tried to install the otmonitor add-on.
I get a slightly different error message:

The command '/bin/bash -o pipefail -c ./tclkit sdx.kit wrap otmonitor -runtime runtime && cp otmonitor /opt/otmonitor && chmod +x /opt/otmonitor' returned a non-zero code: 127

**Comment by basnijholt** [comment]
I have just tried to install this add-on on a Raspberry Pi 4 running 32bit OS.

I find this in my supervisor log (`http://192.168.1.3:8123/hassio/system`):
```
20-12-20 14:49:56 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/basnijholt/addon-otmonitor repository
20-12-20 14:49:57 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 1 new - 0 remove
20-12-20 14:50:01 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/a7902f0f_otmonitor
20-12-20 14:50:01 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for a7902f0f/armv7-addon-otmonitor:dev
20-12-20 14:51:02 INFO (SyncWorker_3) [supervisor.docker.addon] Build a7902f0f/armv7-addon-otmonitor:dev done
20-12-20 14:51:02 INFO (MainThread) [supervisor.addons] Add-on 'a7902f0f_otmonitor' successfully installed
```

and this is the log once I start ot-monitor:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: otmonitor
 otmonitor add-on by Bas Nijholt
-----------------------------------------------------------
 Add-on version: dev
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 5.8  (armv7 / raspberrypi4)
 Home Assistant Core: 2020.12.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] otmonitor.sh: executing... 
[15:51:19] INFO: Initializing the config overwriting.
[15:51:19] INFO: Finished the config overwriting.
[cont-init.d] otmonitor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:51:19] INFO: Starting otmonitor...
[15:51:20] INFO: Starting NGinx...
```

@JarichSpliethoff, I am not sure why you are seeing problems, could you paste the entire error message from your Supervisor log?

**Comment by JarichSpliethoff** [comment]
I installed 64bit OS on the Raspberry Pi 4B 8GB as that one was recommended:
![afbeelding](https://user-images.githubusercontent.com/22955519/102750018-60386a80-4365-11eb-8dfb-abeb24c87699.png)
https://www.home-assistant.io/hassio/installation/

This is what the Supervisor log shows:

`20-12-21 07:21:27 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for a7902f0f/aarch64-addon-otmonitor:dev
20-12-21 07:21:31 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build a7902f0f/aarch64-addon-otmonitor:dev: The command '/bin/bash -o pipefail -c ./tclkit sdx.kit wrap otmonitor -runtime runtime &&     cp otmonitor /opt/otmonitor &&     chmod +x /opt/otmonitor' returned a non-zero code: 127
20-12-21 07:21:31 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/21 : ARG BUILD_FROM=hassioaddons/debian-base
Step 2/21 : FROM ${BUILD_FROM}
 ---> 5e2a9db785a7
Step 3/21 : RUN apt-get update     && apt-get install -y --no-install-recommends         nginx         wget         python3-tk     && rm -fr         /tmp/*         /etc/nginx         /var/{cache,log}/*         /var/lib/apt/lists/*         && mkdir -p /var/log/nginx     && touch /var/log/nginx/error.log
 ---> Using cache
 ---> 26b23877f037
Step 4/21 : COPY rootfs /
 ---> Using cache
 ---> b58538007023
Step 5/21 : ARG BUILD_ARCH=amd64
 ---> Using cache
 ---> 214d560bee72
Step 6/21 : ARG BUILD_DATE
 ---> Using cache
 ---> 609a882007b7
Step 7/21 : ARG BUILD_REF
 ---> Using cache
 ---> ed51e35ed54a
Step 8/21 : ARG BUILD_VERSION
 ---> Using cache
 ---> cb40282ef8df
Step 9/21 : RUN apt update && apt install wget unzip -y
 ---> Using cache
 ---> b48713646b2a
Step 10/21 : WORKDIR /tmp
 ---> Using cache
 ---> 34fdd60ae6cd
Step 11/21 : RUN wget https://github.com/hvxl/otmonitor/archive/master.zip &&     unzip master.zip && mv otmonitor-master /otmonitor
 ---> Using cache
 ---> f1c8f1d66523
Step 12/21 : WORKDIR /otmonitor
 ---> Using cache
 ---> 0a00a8c27f30
Step 13/21 : RUN wget -O sdx.kit https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/tclkit/sdx-20110317.kit &&     if [[ "${BUILD_ARCH}" = "aarch64" ]]; then URL_BASE="tclkit-aarch64"; fi &&     if [[ "${BUILD_ARCH}" = "amd64" ]]; then URL_BASE="tclkit-x64"; fi &&     if [[ "${BUILD_ARCH}" = "armhf" ]]; then URL_BASE="tclkit-ahf"; fi &&     if [[ "${BUILD_ARCH}" = "armv7" ]]; then URL_BASE="tclkit-ahf"; fi &&     if [[ "${BUILD_ARCH}" = "i386" ]]; then URL_BASE="tclkit"; fi &&     wget -O tclkit http://otgw.tclcode.com/download/${URL_BASE} &&     cp tclkit runtime &&     chmod +x tclkit
 ---> Using cache
 ---> e6ef4174865b
Step 14/21 : RUN ./tclkit sdx.kit wrap otmonitor -runtime runtime &&     cp otmonitor /opt/otmonitor &&     chmod +x /opt/otmonitor
 ---> Running in 5e447f5b95a6
./tclkit: error while loading shared libraries: libdbus-1.so.3: cannot open shared object file: No such file or directory

Removing intermediate container 5e447f5b95a6
`

@basnijholt , probably because I'm running the 64bit OS?

**Comment by basnijholt** [comment]
> @basnijholt , probably because I'm running the 64bit OS?

By Googling the error message, I indeed come to that conclusion... I have no idea why this happens though.

**Comment by JarichSpliethoff** [comment]
ok, at least thanks for your you support so far!
