### ISSUE TITLE
Adding custom changes to html to the docroot at build time

### ISSUE THREAD

**Issue by fliphess** [basnijholt/addon-otmonitor#12]
Hey Bas! 

Thanks for addon! 

I'm migrating from home-assistant manually installed in a virtualenv to supervised and figuring out how to replace the services I'm running with addons.  

I'm currently looking for a replacement for otmonitor and then I've found this addon. Lovely! 

In my current otmonitor I'm making some changes to the HTML in the docroot prior to building the binary (mostly css changes)

I'd love to create a PR adding this, but If you are hesitant to support it to prevent future issues, I'm open to creating a fork for personal use. 

Are you open to supporting such a change?

**Comment by fliphess** [comment]
To be precise: I'd like to create a PR that offers a mechanism for adding custom changes to the addon rather than creating a PR with my custom changes: )

**Comment by basnijholt** [comment]
Hi @fliphess, that sounds great!

Do you have an example (screenshot perhaps) of how your otmonitor interface looks like?

**Comment by fliphess** [comment]
Hey @basnijholt 

Off course :) 

I've taken lots from other repositories and copied stuff around (IE: https://github.com/timoline/OTGW), and it's not very pretty mainly because I'm not a web developer (read: I have no taste whatsoever when it comes to user interfaces). 

By making it possible in this addon to change the styling there might be some other people that are willing to make a shiney theme :)

My OTGW is not connected to the boiler atm due to a recent move, so it's not showing any real data:

![Screenshot 2020-12-31 at 11 54 14](https://user-images.githubusercontent.com/2484666/103407667-c2604f00-4b5f-11eb-8c4f-c773ce3d231f.png)
![Screenshot 2020-12-31 at 11 53 57](https://user-images.githubusercontent.com/2484666/103407669-c3917c00-4b5f-11eb-99fe-d86d3565483b.png)
![Screenshot 2020-12-31 at 11 53 44](https://user-images.githubusercontent.com/2484666/103407670-c42a1280-4b5f-11eb-8523-f70516200841.png)

**Comment by fliphess** [comment]
Oh btw there's two ways of adding your own pages and adjustments:

- Adding a custom html directory that overrules the files in the embedded docroot (I've had some issues but I'm not sure what it was)
- Replacing the files in the embedded docroot prior to building (The method I'm currently using) 

I'll do some research why the intended method of the custom html directory didn't work for me at the time and fix the code accordingly as I think that's the nicest way of accomplishing this.
