### ISSUE TITLE
New supervisor 2021.02.5- 'startup' deprecated error

### ISSUE THREAD

**Issue by andriej** [basnijholt/addon-otmonitor#27]
`21-02-08 11:02:26 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of otmonitor` in latest stable Supervisor: `2021.02.5`

**Comment by ookonbekend** [comment]
First, many thanks for this useful Add-On!

Btw, of course same warning here in core-2021.3.3

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of otmonitor

**Comment by fliphess** [comment]
I haven't upgraded to the newer core and supervisor yet so I haven't seen it yet, but this is planned for this weekend. 
I think I can make a fix later next week :)

**Comment by ookonbekend** [comment]
Much appreciated, many thanks in advance!
