### ISSUE TITLE
After a container restart Alerts, Web Server lose their config

### ISSUE THREAD

**Issue by mihsu81** [basnijholt/addon-otmonitor#31]
Hi @basnijholt,

After a restart of the container the Alerts and Web Server tabs lose their config.

Also the settings added in the ThingSpeak tab are lost after navigating away from the tab.

Thank you in advance for your help in getting this solved.
Mihai

**Comment by fliphess** [comment]
@mihsu81 

I'm afraid you are correct: On container start some updates on the configuration are done using a startup script, but the config itself is very stateless and as such on container restart the manually configured settings are gone. 

I'd love to make some edits to change this, but I'm currently a bit busy with other things.

I'll keep this issue open so if I can find some time to change this, I can have a look! :)

**Comment by mihsu81** [comment]
Hi @fliphess,
I've made some adjustments in a fork of your repo to include E-mail and ThingSpeak settings and added 3 more MQTT settings (All Messages, QOS and Retransmit). If you'd like I can do a PR.
Thanks.

**Comment by fliphess** [comment]
Hey @mihsu81 

I'd love to add it! 

Feel free to create a PR so we can merge it in over here :)

**Comment by fliphess** [comment]
I've merged your PR, I think  we can close this :) 

If you think we should reopen it, please let me know :) Thanks a lot! 👍 🥇
