### ISSUE TITLE
Can't install anymore

### ISSUE THREAD

**Issue by andriej** [basnijholt/addon-otmonitor#33]
```
 ---> 6301732f4be4
Step 7/27 : ARG BUILD_ARCH
 ---> Using cache
 ---> 623f7c2c3f0d
Step 8/27 : SHELL ["/bin/bash", "-o", "pipefail", "+x", "-c"]
 ---> Using cache
 ---> 21c831cd8613
Step 9/27 : WORKDIR /otmonitor
 ---> Using cache
 ---> 1ebe80d61eb6
Step 10/27 : RUN apt-get update  && apt-get install -y --no-install-recommends wget  && wget -qO /tmp/otm.tgz https://github.com/hvxl/otmonitor/archive/master.tar.gz  && tar xzf /tmp/otm.tgz --strip=1 -C .  && rm /tmp/otm.tgz  && wget -qO ./sdx.kit https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/tclkit/sdx-20110317.kit   && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then URL_BASE="tclkit-aarch64"; fi  && if [[ "${BUILD_ARCH}" = "amd64" ]]; then URL_BASE="tclkit-x64"; fi  && if [[ "${BUILD_ARCH}" = "armhf" ]]; then URL_BASE="tclkit-ahf"; fi  && if [[ "${BUILD_ARCH}" = "armv7" ]]; then URL_BASE="tclkit-ahf"; fi  && if [[ "${BUILD_ARCH}" = "i386" ]]; then URL_BASE="tclkit"; fi  && wget -qO tclkit https://otgw.tclcode.com/download/${URL_BASE}  && cp tclkit runtime  && chmod +x tclkit  && ./tclkit sdx.kit wrap otmonitor -runtime runtime
 ---> Running in 9584e930cfdc
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [308 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [15.2 kB]
Fetched 8469 kB in 3s (2996 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libpcre2-8-0
The following NEW packages will be installed:
  libpcre2-8-0 wget
0 upgraded, 2 newly installed, 0 to remove and 32 not upgraded.
Need to get 1115 kB of archives.
After this operation, 3925 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libpcre2-8-0 amd64 10.32-5 [213 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 wget amd64 1.20.1-1.1 [902 kB]
debconf: delaying package configuration, since apt-utils is not installed

Fetched 1115 kB in 0s (5081 kB/s)
Selecting previously unselected package libpcre2-8-0:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 6918 files and directories currently installed.)
Preparing to unpack .../libpcre2-8-0_10.32-5_amd64.deb ...
Unpacking libpcre2-8-0:amd64 (10.32-5) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.20.1-1.1_amd64.deb ...
Unpacking wget (1.20.1-1.1) ...
Setting up libpcre2-8-0:amd64 (10.32-5) ...
Setting up wget (1.20.1-1.1) ...
Processing triggers for libc-bin (2.28-10) ...
Removing intermediate container 9584e930cfdc
```

While trying to install on latest superrvisor and Debian 11.1 I see error as above.
There was no issue with Debian 11.0.

**Comment by fliphess** [comment]
Hey @andriej 

Thanks for filing this issue! Could it be possible that you've left some error output out? The output you've posted is not obviously showing anything that is broken so I'm guessing a bit what could be wrong...

I'm working on an upgrade of the container from buster to bullseye myself (See: #34), but so far I didn't run into any issues yet...

If you happen to have some more details about why you cannot install anymore, that would be highly appreciated!

**Comment by andriej** [comment]
Unfortunately not, I've managed to recover the addon from backup (and it's working).

**Comment by fliphess** [comment]
Could you perhaps try to login on your home assistant machine and run `journal -xef` and do a reload and a rebuild of the addon in the supervisor panel? 

There might be some related output why the container build is stopping halfway without any other mention....

**Comment by fliphess** [comment]
Hey @andriej 

In a recent issue (#41) you mentioned you got it working again... 

Does that imply we can close this issue?

**Comment by andriej** [comment]
This issue was on previous machine and since I didn't update otmonitor (after recovering from backup) I'm not sure if it's fixed.
On new system it works tho.

It would be nice to have addon releases numbered, so HA would show updates of it too. :)

**Comment by fliphess** [comment]
Hey @andriej 

I'd love to do that eventually, but for now it's a bit more work than I'd like to spend on this addon :) 
Setting up a container build is quite a bit of work because it requires active versioning and pushing containers to the registry from a pipeline using api tokens (that need rotation, maintenance, a docker account etc).... 

For now it's just a lot easier for us to stick with the `dev` version because it's only requires a merge to master without having to deal with all the moving parts of creating a new versioned release, managing the container image build and setting up and maintaining a build pipeline.

Maybe I'll add it sometime in the future (Or @basnijholt if he is in the mood to get wild on github actions), but don't expect it any time soon as this way it keeps the maintenance on this addon as simple as possible, sorry.

**Comment by andriej** [comment]
Oh, I totally didn't know that (complexity that versioning introduces)

Thanks for clarification, this addon is must have - versioned or not :)

**Comment by fliphess** [comment]
Always a pleasure, never a chore :) 👍  

I'll close this issue for now, if the issue re-appears we can always re-open it or create a new issue to investigate what's going on....
