### ISSUE TITLE
Override mode is not set as well as other settings. 

### ISSUE THREAD

**Issue by iamkarlson** [basnijholt/addon-otmonitor#4]
Hi,
I've run an addon with appropriate settings for MQTT/OTGW. However, if I open a web UI from the addon page I can see some data but can't change any settings. Button Done which appears in non-daemon version of the app is not visible in the addon.

![image](https://user-images.githubusercontent.com/4534374/93820317-43ed3a80-fc5d-11ea-9a73-57a77d481684.png)
![image](https://user-images.githubusercontent.com/4534374/93820505-8f074d80-fc5d-11ea-9f75-eb6c47b3a2f1.png)

Is there anything I can try to get the settings working? Did you experience such an issue?

**Comment by basnijholt** [comment]
Right! You should change some of those settings in the Supervisor add-on configuration screen, like:
![image](https://user-images.githubusercontent.com/6897215/93820843-0a68ff00-fc5e-11ea-8aa3-1efd1d0e4d87.png)

Does that solve your problem?

**Comment by iamkarlson** [comment]
That's are my settings:
![image](https://user-images.githubusercontent.com/4534374/93821117-6b90d280-fc5e-11ea-8ba4-353cd8ea0976.png)

Of course, those which are blurred they are correct.

**Comment by basnijholt** [comment]
I guess this is fixed now?

I see that this was because of the old binaries (https://github.com/hvxl/otmonitor/issues/9).
