### ISSUE TITLE
Connect over serial?

### ISSUE THREAD

**Issue by Mrten** [basnijholt/addon-otmonitor#40]
My otgw is connected directly via serial, but it seems the config has a fixed `type tcp`. Would you consider adding an option to make that configurable?

**Comment by fliphess** [comment]
@Mrten If you can get it to work on a local fork: Sure! We'll merge it :) 👍 

I'm not sure if/how it's possible to pass your serial to a container.... You could have a look how it's done in the [zigbee2mqtt addon](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt): They do some serial stuff  so you might be able to use some of their config as an example.

Please make `tcp` the default so the addon doesn't break for current users and add some documentation so even lesser-technical  users know how to configure it and keep me posted, I can always provide some input on how to proceed :)

I'm a bit busy lately so if I don't respond in time on your PR, please do some highlighting so I get some notifications here and there :) (I won't be able to test it myself as my otmonitor is at the other side of the house so please paste some log output in the PR so we have some basic idea it's working :) 

Thanks!

**Comment by fliphess** [comment]
As this was merged in #44: Let's close this one :)
