### ISSUE TITLE
s6-overlay-suexec

### ISSUE THREAD

**Issue by endsideX** [basnijholt/addon-otmonitor#43]
Many thanks for this super helpful addon. 
Unfortunately, since an HA update I always get the following message and the addon no longer starts.

`s6-overlay-suexec: fatal: can only run as pid 1`

Is there anything I can do to get it to start again?

**Comment by fliphess** [comment]
Hey @endsideX !  

Can you try rebuild the addon? I've pushed some fixes earlier this week that should take care of it :) 

This plugin does not provide a pre-build docker container, so to make sure you use the latest version, navigate to the addons dashboard in home assistant, select the "addon store" and from the "kebab menu" (The three dots in the right corner), click "check for updates": 
![Screen Shot 2022-06-19 at 19 01 45](https://user-images.githubusercontent.com/2484666/174492327-8a7c003f-40b9-4574-ba14-49cba2088681.png)

After that, you can rebuild the addon and things should work again.... 

Let me know if you can't get it to work :) 👍

**Comment by endsideX** [comment]
Thank you very much for the effort and please excuse the late reply. I have just found errors in my configuration. Now everything works perfectly again.

**Comment by fliphess-tiqets** [comment]
> Now everything works perfectly again.

Perfect! Thanks for responding :) I'll close this one 👍
