### ISSUE TITLE
I cannot commit to this repository anymore

### ISSUE THREAD

**Issue by fliphess** [basnijholt/addon-otmonitor#47]
Hey @basnijholt! 

This weekend I made the big decision and bought a Plugwise Anna thermostat and got rid of my OpentTerm gateway.  (They're really affordable in the summer 👍 )

Because of this, I'm not in the position anymore to commit to this project.
I won't be watching for new issues to push fixes in the future, so for the sake of the principle of least permissions,  I think it would be wise to remove my merge permissions. 

Thanks a lot for your trust and intentions giving me commit rights and the freedom to push a lot of improvements to this repository, I had a lot of fun doing so :) 

See you around! 

-X- 

Flip 

(I will close this issue in a few days, as it's not related to anything that requires fixing)

**Comment by basnijholt** [comment]
First off, congrats on the new Plugwise Anna thermostat! I hope you enjoy working with it as much as I've enjoyed having you contribute to this project.

I want to extend a sincere thank you for all the hard work, dedication, and valuable contributions you've made. It's been a great to work alongside you, and your efforts have genuinely made a significant difference here.

Best of luck in your future endeavors 😄
