### ISSUE TITLE
Does not build on raspberry

### ISSUE THREAD

**Issue by DJJo14** [basnijholt/addon-otmonitor#6]
It does not build on any other arch than amd64, because you are downloading a x64 binary

a quick test changing the BUILD_ARCH and download, seem to install, [see](https://github.com/DJJo14/addon-otmonitor/pull/1)

Not tested is the running state.

**Comment by DJJo14** [comment]
The fault comes from 8f147c055593fcecbc3939f3362cd8b36702dce1 where the source gets downloaded but de toolkit is fixed on x64

**Comment by basnijholt** [comment]
I just pushed https://github.com/basnijholt/addon-otmonitor/commit/a2bc1fbf7011ea13cec9ef909127f49e5e4955c6.

Can you try if it works?

**Comment by basnijholt** [comment]
I just tried it on my RPi4 and it seems to work :tada:
