### ISSUE TITLE
Add websocket to nginx

### ISSUE THREAD

**Issue by andriej** [basnijholt/addon-otmonitor#9]
Currently, even when using proper setup with SSL, in "messages" there's an error about websocket in browser.
Adding otmonitor webpage to nginx-proxy with websocket support makes it working properly (so the messages and charts update themselves automatically).

I think it's worth adding in nginx configuration

**Comment by basnijholt** [comment]
I agree!

However, unfortunately, I currently have no time to figure out how to do it.

If you figure it out, please create a PR 👍

**Comment by andriej** [comment]
I will try to dig into that later, as turning on websocket doesn't solve the issue.
It's HA's ingress that's causing some files to be 404 error.

Not a priority, as it works tho.

**Comment by fliphess** [comment]
I suspect this has something to do with the newer ciphers for tls1.3 that do not work for tls1.2 (websockets do not support 1.3 yet afaik) 

I'm running into this issue myself with my setup and use of the companion app, so I've to do some debugging anyway. I think I can create a fix later this month.

**Comment by fliphess** [comment]
I've created a [merge request upstream](https://github.com/hvxl/otmonitor/pull/15) that should fix this issues :)

**Comment by basnijholt** [comment]
Nice! I see it's merged upstream. Do we require any changes here?

**Comment by fliphess** [comment]
I don't think so: We build straight from master so reloading and rebuilding the container should work :)

**Comment by fliphess** [comment]
I think we can close this one can't we? :)

**Comment by basnijholt** [comment]
Yes, you fixed that one 😇
